[project]
name = "ha-mcp"
version = "0.1.0"
description = "This a simple Home Assistant MCP server. Nothing fancy, just basics functionalities"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.8.1",
    "requests>=2.32.3",
]
